# Book settings
# Learn more at https://jupyterbook.org/customize/config.html


title: BoBiAC Book
author: Image Analysis Collaboratory @ Harvard Medical School
copyright: "2025"
logo: _static/logo/bobiac_logos_svgexport-03.svg

exclude_patterns: [_build, .DS_Store, "**.ipynb_checkpoints", README.md]

# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: cache # "off", "force", "cache", "auto"

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

# Information about where the book exists on the web
repository:
  url: https://github.com/HMS-IAC/bobiac/  # Online location of your book
  branch: main  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
# NOTE: Jupyter Book assumes everything under _static/ is the root for custom assets.
html:
  use_repository_button: true
  extra_footer: |
      <p>
      All content is licensed under <a href="https://creativecommons.org/licenses/by/4.0/" target="_blank">CC-BY 4.0</a>, except where noted otherwise.
      </p>

  # NOTE: When running `jupyter-book build`, a `_static/` folder is generated that includes `styles` and `scripts` directories automatically.
  # Since we are placing our custom CSS and JS in folders named `styles/` and `scripts/`, Jupyter Book will automatically include them.
  # Therefore, it is not necessary to manually specify `extra_css` or `extra_javascript` in the config.
  # Example (not needed):
  # extra_css:
  #   - styles/custom.css
  # extra_javascript:
  #   - scripts/custom.js
  extra_css:
    - https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css
